# Generated by Django 5.0.14 on 2026-09-17 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('waiter', 'Waiter'), ('kitchen', 'Kitchen Staff')], default='waiter', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active_staff', models.BooleanField(default=True, help_text='Deactivate to revoke dashboard access without deleting the account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
